### ISSUE TITLE
Redactar un FAQ

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#1]
Voy a ponerme a redactar un FAQ para el foro, que explique su uso y su motivación. Podemos escribir en esta issue las preguntas y respuestas que debería tener.

(@pbaeyens: Añado una lista de posibles preguntas a redactar)
- [x] ¿Qué es la categoría Meta?
- [x] [¿Qué significa que una respuesta ha sido aceptada?](http://stackoverflow.com/help/accepted-answer)
- [x] [¿Cómo debería preguntar/responder?](http://stackoverflow.com/help/behavior)
- [x] ¿Qué son las medallas?

**Comment by mroman42** [comment]
**¿Cómo puedo registrarme?**
_El registro y el login en el foro se hacen a través de una cuenta en GitHub. Si no tienes una, puedes crearla en github.com. GitHub es una plataforma de desarrollo de software colaborativa, basada en el sistema de control de versiones git. Una vez tengas la cuenta, el foro te pedirá que cedas permisos sobre ella para leer información pública y podrás entrar en tu cuenta._

**Comment by mroman42** [comment]
**¿Puedo responderme a mí mismo?**
_Sí, y además puedes aceptar tu propia respuesta si consideras que era la más apropiada a la pregunta original. De hecho, es un mecanismo útil si quieres subir una relación de ejercicios resuelta en forma de preguntas y respuestas para discutirla o buscar soluciones alternativas._

**Comment by mroman42** [comment]
**¿Sobre qué puedo preguntar?**
_Cualquier problema o duda relacionada con las matemáticas o la ingeniería informática. Además, cualquier duda relacionada con este mismo foro._
_Evita aquellas preguntas en las que:_
- _Cualquier respuesta es válida: "¿Cuál es tu ___ favorito?"_
- _No hay ningún problema a resolver: "¿Qué pensáis sobre ___?"_
- _Hay preguntas hipotéticas imposibles de responder: "¿Qué pasaría si Hitler no hubiera nacido?"_
- _No preguntas sobre un problema específico: "¿Cómo se hace la práctica de __?"_
- _Se debe resolver un trabajo en su totalidad antes de la fecha de entrega_

_Puedes usar [el foro](http://dgiim.github.io/foro/) para discutir algunas de estas cuestiones._

**Comment by oxcar103** [comment]
Creo que en la pregunta "¿Sobre qué puedo preguntar?" deberíamos aclarar lo de que no se pongan preguntas de "hazme los deberes"
(Con mejor labia que lo que he puesto  :sweat_smile:)

**Comment by mroman42** [comment]
**¿Es sólo para alumnos del doble grado?**
_¡No! Aunque el blog y el foro los empezamos entre alumnos del doble grado de la Universidad de Granada y la temática está orientada a sus materias, queremos que sean útiles a cuanta más gente mejor. Queremos llegar a todo aquél que le pueda ser útil y animamos especialmente a quien no estudie en el doble grado a participar._

**Comment by mroman42** [comment]
@oxcar103 Intentad redactarla alguno, por favor. Yo llevo un rato sin que me salga.

**Comment by mroman42** [comment]
**¿Cuándo debo usar comentarios y cuando respuestas?**
_Generalmente, una respuesta debe proponer una contestación más o menos completa a la pregunta y no debe usarse para debatir sobre otras respuestas. Los comentarios sirven para dar un debate breve sobre aspectos concretos de las preguntas y las respuestas. Otro posible uso de los comentarios es permitir a quien preguntaba que confirme que la respuesta funciona._

**Comment by mroman42** [comment]
**¿Cómo puedo escribir matemáticas?**
_Las matemáticas pueden incluirse de dos maneras, una escribiendo en la misma línea con `\\( ... \\)`, y otra escribiéndolas como una ecuación separada con `$$ ... $$`. Entre estos marcadores debe escribirse usando sintaxis de MathJax, que es similar a la de LaTeX y se explica detalladamente [aquí](http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)._

**Comment by mx-psi** [comment]
~~No sé cómo es la sintaxis así que por favor que alguien añada el resto:~~
**¿Cómo puedo escribir código?**
_El foro procesará como bloques de código los párrafos indentados por 4 espacios. El coloreado de código se realiza usando highlight.js, que detecta automáticamente el lenguaje._

_Escribe siempre el ejemplo más conciso que reproduzca tú error. Asegúrate de que tú código sólo tiene el error que quieres resolver y de que puede ejecutarse sin necesidad de añadir código adicional._

**Comment by mroman42** [comment]
_El foro procesará como bloques de código los párrafos indentados por 4 espacios. El coloreado de código se realiza usando highlight.js, que detecta automáticamente el lenguaje._

**Comment by mroman42** [comment]
**¿Qué es la categoría Meta?**
Es la categoría que engloba todas aquellas preguntas relacionadas con el foro en sí. Cómo escribir, cómo responder o cómo participar. Todas las preguntas de este FAQ son buenos ejemplos del tipo de preguntas que se pueden responder allí.

**Comment by mroman42** [comment]
**¿Qué significa que una respuesta ha sido aceptada?**
Significa que esa respuesta sirvió a aquél que preguntó. No siempre es un indicador de que sea una respuesta perfecta o la mejor, ni debe tomarse como un cierre definitivo de la pregunta.

**Comment by mroman42** [comment]
En la de cómo preguntar/responder, casi copiaría literalmente a SO: http://stackoverflow.com/help/behavior. Enlazarlo no me parece mala idea.

**Comment by mx-psi** [comment]
**¿Qué son las medallas?**
_Recibes medallas cuando realizas aportaciones importantes a dgiimOverflow. Puedes encontrar una lista de medallas aquí_ (Falta añadir enlace cuando instalemos el plugin). _Puedes ver las medallas que un usuario ha conseguido en su perfil._

**Comment by mx-psi** [comment]
**¿Cómo debo preguntar/responder?**
- **Sé honesto**. Si ves información incorrecta, vota hacia abajo y añade comentarios especificando el error. Edita y mejora las preguntas y respuestas existentes.
- **Sé amable**. Estamos aquí para aprender juntos. Sé educado, paciente y asume buenas intenciones.
- **No utilices saludos, eslogans o firmas**. Añaden ruido innecesario. Todos tus posts enlazan a tu perfil, que puedes rellenar como quieras.

_Adaptado de [StackOverflow](http://stackoverflow.com/help/behavior)_
