### ISSUE TITLE
Solapamiento del menú de navegación

### ISSUE THREAD

**Issue by robertohueso** [libreim/overflow#11]
En pantallas pequeñas (Móviles) al pulsar el botón del menú principal y luego el de login se solapan.
![screenshot_2016-03-02-21-32-50](https://cloud.githubusercontent.com/assets/9488024/13474471/6bdbb8a6-e0be-11e5-909b-2a386976ef93.png)

**Comment by mroman42** [comment]
Además pulsando primero login y luego el menú no se solapan sino que se retira uno y queda el otro, es un comportamiento un poco incoherente.

**Comment by mroman42** [comment]
Solucionado. He vuelto a comprobar que funcionase correctamente.

**Comment by mroman42** [comment]
Ahora al pulsar el menú de login cuando está en la pantalla de ordenador, se borran los iconos de la  parte superior, que serían el equivalente en la pantalla grande al menú de navegación.
