### ISSUE TITLE
Mensajería privada y wall posts

### ISSUE THREAD

**Issue by mx-psi** [libreim/overflow#14]
Q2A permite mensajes privados entre usuarios y publicar en los perfiles estos.
**¿Deberíamos dejar habilitada esa opción?**
De momento lo dejo desactivado.

**Comment by mroman42** [comment]
Creo que no es necesaria. Tenemos herramientas de comunicación entre nosotros mejores que esa. Quizá habría que plantearse algo que sirva para discutir los problemas públicamente, algo como el chat de SE, pero creo que la solución a esto no es la mensajería entre usuarios.

**Comment by mroman42** [comment]
Cierro esta issue. Si en algún momento es necesaria, puede reabrirse.
