### ISSUE TITLE
Evitar ver la solución a un problema

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#15]
Quizá sería útil un mecanismo que permita ver el enunciado evitando ver la solución al problema, de forma que uno pueda intentarlo con el enunciado allí evitando ver por accidente la solución.

**Comment by MartaAndres** [comment]
Parece que se puede modificar el css, a lo mejor se puede hacer algún efecto "spoiler" con eso?
Que al hacer clic (o mover el ratón, según lo que queramos) en una respuesta se muestre la respuesta?

**Comment by mroman42** [comment]
He abierto una [pregunta](http://www.question2answer.org/qa/51005/show-question-without-answers?show=51014#c51014) en el foro de Q2A por si alguien tiene una solución rápida.

Mi idea ahora mismo es intentar copiar el sistema que hace que los comentarios se oculten cuando son muchos (véase esta [pregunta](http://tux.ugr.es/dgiimoverflow/index.php/12/curva-plana-perpendicular-todas-las-rectas-pasan-por-origen) en nuestro foro ) y poner un botón grande abajo que muestre todas las respuestas cuando se pulsa. Imagino que para eso habrá que tocar el núcleo de q2a, pero me gustaría mucho poder hacerlo.

**Comment by mroman42** [comment]
Copio la respuesta de que he obtenido en el [foro](http://www.question2answer.org/qa/51005/show-question-without-answers?):

>  Answer by jatin.soni:
> 
> 1st and easy way is to use jQuery. What you need to do is add a checkbox or a text link or element and than by default hide entire Answers container (parent container is .qa-a-list)
> 
> Now if the use want to see other answer, s/he will click on the checkbox or text link to unhide all answers otherwise he will write own and submit.

Es decir, que habrá que tocar en el núcleo para hacerlo. He tocado muy poco cosas de programación web, así que voy a intentarlo pero no será rápido. Si alguno se atreve con esto, que se asigne.

**Comment by mroman42** [comment]
Copiando este código en el HTML arbitrario que nos dejan incluir desde el panel de administración, funciona:

``` HTML
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
$(document).ready(function () {
    $( ".qa-part-a-list" ).toggle();
    var hidebutton = $('<button class="qa-form-light-button qa-form-light-button-answer">Show answers</button><br></br>').click(function () { $( ".qa-part-a-list" ).toggle( "slow" ); });
    hidebutton.appendTo( $(".qa-part-a-form") );
});
</script>
```

El resultado no es especialmente elegante, pero cumple lo que tiene que cumplir. Si a alguien se le ocurre cómo dejarlo un poco más bonito (centrando el botón, o algo así), se agradece.

**Comment by mroman42** [comment]
Hecho, usando el HTML anterior.

**Comment by mroman42** [comment]
He vuelto a retirar el trozo de script que ocultaba preguntas.
