### ISSUE TITLE
Copias de seguridad de la BD

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#17]
Hace falta algo para evitar perder todos los datos. Tienen bastante valor muchas cosas de las que vamos a meter ahí.

**Comment by mroman42** [comment]
Un script para copiar la BD en ordenadores nuestros estaría muy bien. Lo podríamos activar cada cierto tiempo con `cron`.

**Comment by mroman42** [comment]
Entiendo que este comando debería servir. No lo puedo probar porque no tengo acceso aquí al `ssh`. Si alguien con acceso ( @fdavidcl  @pbaeyens ) me confirma que funciona, cierro issue.

``` bash
mysqldump -u dgiim -p -h tux.ugr.es QA > backupdgiimoverflow.sql
```

**Comment by fdavidcl** [comment]
Funciona esto:

``` bash
# Desde el server
mysqldump -u dgiim -p QA > backup.sql

# En local
ssh -C dgiim@tux.ugr.es mysqldump -u dgiim -p QA > backup.sql
```

**Comment by mroman42** [comment]
Pero eso copia en el propio servidor, ¿no? Mi idea era clonarla cada cierto tiempo en nuestro propio ordenador para prevenir un posible fallo en `tux`.

**Comment by fdavidcl** [comment]
Nop, el segundo comando lo clona al propio ordenador

**Comment by mroman42** [comment]
Pues con que nos aseguremos de ir haciéndolo cada cierto tiempo, puedo cerrar.
