### ISSUE TITLE
Avatar por defecto

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#19]
Un avatar por defecto a seguramente ayudaría a que la gente se animara a colocar uno propio. Si queremos tenerlo hay que elegir uno.

**Comment by oxcar103** [comment]
Considero que pocos hay mejores que nuestro logo, ¿no?

**Comment by mroman42** [comment]
Hombre, lo que pasa es que el logo es el avatar del bot y queda un poco feo colocárselo a todo el que no tenga. Algo más neutro me gustaría más.

**Comment by mroman42** [comment]
Done
