### ISSUE TITLE
Separación en categorías y tags

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#2]
Hay que decidir un sistema de clasificación de temas usando tags y categorías. Los tags los crea y los elige el usuario, y puede añadir a un tema tantos como quiera; las categorías son fijadas de antemano y cada tema puede asignarse a una de ellas.

**Comment by mx-psi** [comment]
Las categorías que propuso @M42 son:
- Meta
- Matemáticas
  - Análisis
  - Álgebra
  - Geometría
  - Topología
  - Estadística y probabilidad
  - Matemática Aplicada
- Informática
  - Programación
  - Algoritmica y computación
  - Sistemas
  - Datos
  - Arquitectura

Yo apoyo que usemos esas o que usemos solo Meta, Matemáticas e Informática.
Las etiquetas creo que es mejor ir creándolas sobre la marcha y luego moderarlas para que mezclar etiquetas que sean similares. Para inspiración podemos ver las de [MathSE](http://math.stackexchange.com/tags), [SO](http://stackoverflow.com/tags) y [ProgrammersSE](http://programmers.stackexchange.com/tags).

**Comment by mroman42** [comment]
Otra idea es usar como categorías sólo tres (Meta/Informática/Matemáticas) y incluir las subcategorías como etiquetas. Así son más flexibles y nos permiten marcar un problema con varias de ellas.

**Comment by mx-psi** [comment]
Utilizando [este plugin](https://github.com/Towhidn/q2a-tag-descriptions) voto entonces por hacerlo sólo con 3 categorías. Algunas ideas para etiquetas:
- Etiquetas para los lenguajes y programas más utilizados (C++, Maxima, Octave, Java, Ruby...)
- Una etiqueta para cada asignatura
- Etiqueta tipo [reference-request](http://math.stackexchange.com/questions/tagged/reference-request)
- Etiqueta tipo [soft-question](http://math.stackexchange.com/questions/tagged/soft-question)
- Etiqueta sobre instalación de programas/SOs

**Comment by mroman42** [comment]
La idea final es entonces tener 3 categorías y tags. Los tags pueden crearse al principio sin necesidad de puntuación. Conforme vaya avanzando el foro y tengamos cada vez más tags, iremos subiendo el umbral de puntos necesario para crear un nuevo tag.

**Comment by mroman42** [comment]
Cierro, al menos temporalmente.
