### ISSUE TITLE
Sistema de medallas

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#3]
Hay que decidir si activar el sistema de medallas para incentivar al que pregunta y responde (al estilo de SE) y decidir qué medallas se otorgan y bajo qué condiciones.

Con el plugin de medallas vienen por defecto un montón de [medallas de ejemplo](https://github.com/NoahY/q2a-badges#id3), pero podemos elegir sólo aquellas que parezcan más útiles.

**Comment by mx-psi** [comment]
Yo veo interesantes todas las que hay. Las únicas que no me convencen del todo son las del tipo "_Flagged # posts as inappropriate_", porque no sé si nos va a hacer falta realmente (no vamos a ser un sitio tan grande como para necesitar ese nivel de moderación más que en casos excepcionales).

Me ofrezco a traducir las medallas si no lo están ya.

**Comment by mx-psi** [comment]
El _plugin_ que ibamos a usar (el único de medallas, parece) da muchos problemas y no podemos probarlo así que cierro de momento.
