### ISSUE TITLE
Sistema de puntos

### ISSUE THREAD

**Issue by mroman42** [libreim/overflow#4]
Definir el sistema de puntos, por qué acciones se ganan o se pierden y qué privilegios de administración se obtienen con qué puntuaciones.

El sistema por defecto puede consultarse en el FAQ del foro. Los cambios se pueden proponer aquí.

**Comment by mx-psi** [comment]
Posibles privilegios:
- Publicar en _user walls_
- Votar hacia abajo
- Comentar
- Crear etiquetas (habría entonces que decidir etiquetas iniciales en #2 )
- Crear sinónimos de etiquetas (si se puede)
- Marcar preguntas para revisión
- Mezclar preguntas duplicadas
- Editar preguntas/respuestas ajenas

**Comment by mroman42** [comment]
Aquí yo quiero quitar entre los puntos el de votar, hacia arriba o hacia abajo. Motiva a votar siempre, y entiendo que hay veces en las que (si por ejemplo no se entiende del todo o no da tiempo a leer la respuesta) no es bueno votar.

**Comment by josemam** [comment]
Sugiero que en el perfil de los usuarios se desglosen los puntos obtenidos en preguntas de informática y de matemáticas, con rankings separados para ambas categorías.

**Comment by mroman42** [comment]
En StackExchange es así:

```
question is voted up: +5
answer is voted up: +10
answer is marked “accepted”: +15 (+2 to acceptor)
suggested edit is accepted: +2 (up to +1000 total per user)
```

Que me parece una buena guía para seguir. En nuestro caso, propondría que la respuesta aceptada  no fueran tantos puntos (ahora son 30) y quizá daría más al voto arriba/voto abajo (ahora son 1); mas que nada por no diferenciar mucho la primera respuesta de la segunda y que valgan más los votos de todos en conjunto que la aceptación del que escribió la pregunta. Además, quizá simplificaría un poco el sistema quitando peso a cosas como "publicar una pregunta/respuesta".

**Comment by mroman42** [comment]
> @josemam: Sugiero que en el perfil de los usuarios se desglosen los puntos obtenidos en preguntas de informática y de matemáticas, con rankings separados para ambas categorías.

No parece trivial de implementar, creo que lo voy a separar en otra issue.

**Comment by mroman42** [comment]
He marcado los siguientes privilegios:

```
Crear etiquetas: 5 puntos (por ahora)
Votar hacia abajo: 15 puntos
Marcar para revisión: 10 puntos
Comentar: 6 puntos
Editar preguntas ajenas: 100 puntos
```

Los cambios de puntos los dejé de acuerdo a StackExchange. Por ahora puede cerrarse, en el futuro se pueden volver a recalcular puntos si es necesario.
