### ISSUE TITLE
Menú transparente

### ISSUE THREAD

**Issue by mx-psi** [libreim/overflow#6]
El menú de la esquina superior derecha (al pulsar sobre el avatar) se ve transparente en Chromium 48, Firefox 44 y en Chrome para Android y no se ve bien:
![captura de pantalla de 2016-02-29 11-29-44](https://cloud.githubusercontent.com/assets/5502710/13392048/41031b70-ded8-11e5-88d9-209867ece803.png)

**Comment by mx-psi** [comment]
Ahora sólo se ve transparente en la pantalla principal :no_mouth:

**Comment by robertohueso** [comment]
Intento buscar el error pero cuando miro el código de la web que se descarga desde Tux, hay elementos que no encuentro en este repo. Esto me da que pensar que
- Soy yo quien no los encuentra
- El código del repo no es el que funciona en Tux
- Q2A está cargando contenido desde algún servicio externo

**Comment by mroman42** [comment]
El código no es el mismo exactamente. Hay plugins y cosas que no están metidas y en particular hay varios archivos que están fuera porque contenían contraseñas en texto plano. Puedo intentar que se parezcan más subiendo todo lo que pueda y actualizando lo que falte.
