### ISSUE TITLE
Traducir interfaz al castellano

### ISSUE THREAD

**Issue by josemam** [libreim/overflow#9]
Todos los alumnos del doble grado hablamos algo de español y la mayoría de preguntas seguramente estén en español, por lo que tal vez sería deseable que la interfaz estuviese en la lengua de Cervantes, Machado y Belén Esteban. Al menos como opción.

**Comment by mroman42** [comment]
Hay de hecho una traducción completa de Q2A al castellano que podemos usar directamente. Da, de todas formas, algunos problemas con los plugins.

Aunque es previsible que casi todo el que use el foro hable castellano, me parece también que es más fácil esperar de alguien que entienda el inglés a que entienda el castellano. Aquí me gustaría tener opinión general para ver cómo lo hacemos. Yo estaba pensando ayer traducir los tags al inglés y permitir preguntas en inglés.

**Comment by mroman42** [comment]
Como opción sí lo veo clarísimo. Voy a buscar la forma de ponerla.

**Comment by mroman42** [comment]
No parece que haya forma fácil de dejar al usuario la elección de interfaz y, al menos mientras no funcione correctamente con todos los plugins, creo que lo mejor va a ser dejarla en inglés.

**Comment by mroman42** [comment]
Se está usando ahora la traducción. Si hay problemas con ella se pueden abrir otras issues.
